- name: Remove Project db2
  k8s:
    state: absent
    api_key: "{{ db2_k8s_api_key | default(omit) }}"
    host: "{{ db2_k8s_host | default(omit) }}"
    api_version: project.openshift.io/v1
    kind: Project
    name: db2
    namespace: db2
    wait: yes
    wait_sleep: 15
    wait_timeout: 120
