- name: Get DB2uClusters
  k8s_info:
    api_key: "{{ db2_k8s_api_key | default(omit) }}"
    host: "{{ db2_k8s_host | default(omit) }}"
    api_version: db2u.databases.ibm.com/v1
    kind: DB2uCluster
    namespace: db2
  register: clusters

- name: Delete DB2uCluster instance
  k8s:
    state: absent
    api_key: "{{ db2_k8s_api_key | default(omit) }}"
    host: "{{ db2_k8s_host | default(omit) }}"
    api_version: db2u.databases.ibm.com/v1
    kind: DB2uCluster
    name: db2ucluster
    namespace: db2
    wait: yes
    wait_sleep: 15
    wait_timeout: 120
  when: clusters.resources | length > 0

- name: Remove Project db2
  k8s:
    state: absent
    api_key: "{{ db2_k8s_api_key | default(omit) }}"
    host: "{{ db2_k8s_host | default(omit) }}"
    api_version: project.openshift.io/v1
    kind: Project
    name: db2
    namespace: db2
    wait: yes
    wait_sleep: 15
    wait_timeout: 120

- name: Remove ClusterRoleBinding for Norootsquash
  k8s:
    state: absent
    api_key: "{{ db2_k8s_api_key | default(omit) }}"
    host: "{{ db2_k8s_host | default(omit) }}"
    api_version: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    name: db2privileged
    wait: yes
    wait_sleep: 15
    wait_timeout: 120