kind: Deployment
apiVersion: apps/v1
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-app
      component: kibana
  template:
    metadata:
      labels:
        app: kibana-app
        component: kibana
    restartPolicy: Always
    spec:
      containers:
        - name: kibana
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 1Gi
          terminationMessagePolicy: File
          terminationMessagePath: /dev/termination-log
          readinessProbe:
            httpGet:
              path: /app/kibana
              port: 5601
              scheme: HTTP
              httpHeaders:
                - name: Authorization
                  value: "Basic {{BASE64_ELASTIC_CREDENTIALS}}"
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /app/kibana
              port: 5601
              scheme: HTTP
              httpHeaders:
                - name: Authorization
                  value: "Basic {{BASE64_ELASTIC_CREDENTIALS}}"
            initialDelaySeconds: 125
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
          env:
            - name: ELASTICSEARCH_HOSTS
              value: 'https://iaf-system-elasticsearch-es.{{CP4BA_PROJECT_NAME}}.svc.cluster.local:9200'
            - name: ELASTICSEARCH_USERNAME
              value: 'elasticsearch-admin'
            - name: ELASTICSEARCH_PASSWORD
              value: '{{UNIVERSAL_PASSWORD}}'
            - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
              value: 'none'
            - name: LOGGING_VERBOSE
              value: 'true'
          ports:
            - name: kibana-ui
              containerPort: 5601
              protocol: TCP
          imagePullPolicy: Always
          image: "docker.elastic.co/kibana/kibana-oss:{{KIBANA_IMAGE_TAG}}"
  strategy:
    type: Recreate
