# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/latest?topic=manager-configuring-external-database
- name: Get postgresql pod
  kubernetes.core.k8s_info:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    api_version: v1
    kind: Pod
    namespace: postgresql
    label_selectors:
      - app=postgresql
  register: postgresql_pod

- name: ODM DB
  kubernetes.core.k8s_exec:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    namespace: postgresql
    pod: "{{ postgresql_pod.resources[0].metadata.name }}"
    command: >
      bash -c "
        psql postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:5432/postgres <<-EOF
        -- create user odm
        CREATE ROLE odm WITH INHERIT LOGIN ENCRYPTED PASSWORD '{{ cp4ba_postgresql_universal_password }}';

        -- create database odm
        create database odm owner odm template template0 encoding UTF8 ;
        revoke connect on database odm from public;
        grant all privileges on database odm to odm;
        grant connect, temp, create on database odm to odm;

        -- Add table for Execution traces
        \c bas;
        CREATE TABLE EXECUTION_TRACES (
          ID SERIAL8,
          TIME_STAMP INT8,
          LOCATION VARCHAR(2000),
          REQUEST_PATH VARCHAR(2000) NOT NULL,
          CANONICAL_PATH VARCHAR(2000) NOT NULL,
          RULESET_PROPERTIES text,
          ELAPSED_TIME INT8,
          USER_DATA text,
          NB_RULES INT,
          NB_RULES_FIRED INT,
          NB_RULES_NOT_FIRED INT,
          NB_TASKS INT,
          NB_TASKS_EXECUTED INT,
          NB_TASKS_NOT_EXECUTED INT,
          RULES text,
          TASKS text,
          EXECUTION_TRACE_TREE text,
          EXEC_OUTPUT text,
          INPUT_PARAMS text,
          OUTPUT_PARAMS text,
          EXECUTION_ID VARCHAR(255) NOT NULL,
          FULL_EXECUTION_TRACE text,
          CONSTRAINT ET_PK PRIMARY KEY (ID),
          CONSTRAINT EID_UNQ UNIQUE (EXECUTION_ID)
        );
      EOF"
  register: command_status
