- name: Create directory for generated files
  file:
    path: "{{ nexus_output_directory }}"
    state: directory
    mode: u+rwx

- name: Create Project
  include_role:
    name: common
    tasks_from: create-project
  vars:
    common_k8s_api_key: "{{ nexus_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ nexus_k8s_host | default(omit) }}"
    common_namespace_name: nexus
    common_output_directory: "{{ nexus_output_directory }}"

- name: Prepare yaml file for the Operator Group
  template:
    src: operatorgroup.yaml.j2
    dest: "{{ nexus_output_directory }}/operatorgroup.yaml"
    mode: u+rwx

- name: Add the Operator Group
  k8s:
    api_key: "{{ nexus_k8s_api_key | default(omit) }}"
    host: "{{ nexus_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ nexus_output_directory }}/operatorgroup.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Prepare yaml file for the Operator Subscription
  template:
    src: subscription.yaml.j2
    dest: "{{ nexus_output_directory }}/subscription.yaml"
    mode: u+rwx

- name: Add the Operator Subscription
  k8s:
    api_key: "{{ nexus_k8s_api_key | default(omit) }}"
    host: "{{ nexus_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ nexus_output_directory }}/subscription.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Manage Manual Operator common-service
  include_role:
    name: common
    tasks_from: manage-manual-operator
  vars:
    common_k8s_api_key: "{{ nexus_k8s_api_key | default(omit)  }}"
    common_k8s_host: "{{ nexus_k8s_host | default(omit) }}"
    common_namespace_name: nexus
    common_subscription_name: nxrm-operator-certified
    common_deployment_name: nxrm-operator-certified

- name: Wait for NexusRepo CRD to be Established
  include_role:
    name: common
    tasks_from: wait-crd
  vars:
    common_k8s_api_key: "{{ nexus_k8s_api_key | default(omit)  }}"
    common_k8s_host: "{{ nexus_k8s_host | default(omit) }}"
    common_crd_name: nexusrepos.sonatype.com

- name: Prepare yaml file for the Nexus Repo
  template:
    src: nexusrepo.yaml.j2
    dest: "{{ nexus_output_directory }}/nexusrepo.yaml"
    mode: u+rwx

- name: Add the Nexus Repo Instance
  k8s:
    api_key: "{{ nexus_k8s_api_key | default(omit) }}"
    host: "{{ nexus_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ nexus_output_directory }}/nexusrepo.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Wait for Nexus Repo Deployment to be Available
  include_role:
    name: common
    tasks_from: wait-resource-condition
  vars:
    common_k8s_api_key: "{{ nexus_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ nexus_k8s_host | default(omit) }}"
    common_api_version: v1
    common_resource_kind: Deployment
    common_resource_name: nexusrepo-sonatype-nexus
    common_resource_namespace: nexus
    common_condition_name: Available
    common_retries: 80
    common_delay: 15

- name: Get OCP Apps Endpoint
  include_role:
    name: common
    tasks_from: apps-endpoint
  vars:
    common_k8s_api_key: "{{ nexus_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ nexus_k8s_host | default(omit) }}"
    common_output_to_var: "apps_endpoint_domain"
  when: apps_endpoint_domain is not defined

- name: Crete Edge Route
  include_role:
    name: common
    tasks_from: create-edge-route
  vars:
    common_k8s_api_key: "{{ nexus_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ nexus_k8s_host | default(omit) }}"
    common_namespace_name: nexus
    common_route_name: nexus
    common_service_name: nexusrepo-sonatype-nexus-service
    common_wildcard_crt_path: "{{ nexus_wildcard_crt_path }}"
    common_wildcard_key_path: "{{ nexus_wildcard_key_path }}"
    common_ca_crt_path: "{{ nexus_ca_crt_path }}"
    common_apps_endpoint_domain: "{{ apps_endpoint_domain }}"
    common_output_directory: "{{ nexus_output_directory }}"

- name: Change default admin password
  uri:
    url: "https://nexus.{{ apps_endpoint_domain }}/service/rest/v1/security/users/admin/change-password"
    method: PUT
    headers:
      Content-Type: text/plain
    user: admin
    password: admin123
    body: "{{ nexus_universal_password }}"
    validate_certs: false
    force_basic_auth: true
  register: nexus_query_response
  failed_when: >
    (nexus_query_response.status != 204) and
    ('Unauthorized' not in nexus_query_response.msg)

- name: Check if we have the new admin password
  uri:
    url: "https://nexus.{{ apps_endpoint_domain }}/service/rest/v1/security/users/admin/change-password"
    method: PUT
    headers:
      Content-Type: text/plain
    user: admin
    password: "{{ nexus_universal_password }}"
    body: "{{ nexus_universal_password }}"
    validate_certs: false
    force_basic_auth: true
    status_code: 204
  when: ('Unauthorized' in nexus_query_response.msg)

- name: Prepare ldap config json
  template:
    src: ldap-config.json.j2
    dest: "{{ nexus_output_directory }}/ldap-config.json"
    mode: u+rwx

- name: Create LDAP Connection
  uri:
    url: "https://nexus.{{ apps_endpoint_domain }}/service/rest/v1/security/ldap"
    method: POST
    headers:
      Content-Type: application/json
    user: admin
    password: "{{ nexus_universal_password }}"
    src: "{{ nexus_output_directory }}/ldap-config.json"
    validate_certs: false
    force_basic_auth: true
    status_code: 201
  register: nexus_query_response
  failed_when: >
    (nexus_query_response.status != 201) and
    ('Duplicated record' not in nexus_query_response.content)

- name: Prepare nexus role for cpadmins as Nexus admins
  template:
    src: nexus-role.json.j2
    dest: "{{ nexus_output_directory }}/nexus-role.json"
    mode: u+rwx

- name: Create Nexus role for cpadmins as Nexus admins
  uri:
    url: "https://nexus.{{ apps_endpoint_domain }}/service/rest/v1/security/roles"
    method: POST
    headers:
      Content-Type: application/json
    user: admin
    password: "{{ nexus_universal_password }}"
    src: "{{ nexus_output_directory }}/nexus-role.json"
    validate_certs: false
    force_basic_auth: true
    status_code: 200
  register: nexus_query_response
  failed_when: >
    (nexus_query_response.status != 200) and
    ('already exists' not in nexus_query_response.content)

- name: Disable Anonymous access
  uri:
    url: "https://nexus.{{ apps_endpoint_domain }}/service/rest/v1/security/anonymous"
    method: PUT
    headers:
      Content-Type: application/json
    user: admin
    password: "{{ nexus_universal_password }}"
    body_format: json
    body:
      enabled: false
      userId: anonymous
      realmName: NexusAuthorizingRealm
    validate_certs: false
    force_basic_auth: true
    status_code: 200

- name: Create Project
  include_role:
    name: common
    tasks_from: create-project
  vars:
    common_k8s_api_key: "{{ nexus_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ nexus_k8s_host | default(omit) }}"
    common_namespace_name: "{{ nexus_output_namespace }}"
    common_output_directory: "{{ nexus_output_directory }}"
    common_project_output_name: "nexus-output-project.yaml"

- name: Prepare Maven Settings
  template:
    src: maven-settings.xml.j2
    dest: "{{ nexus_output_directory }}/maven-settings.xml"
    mode: u+rwx

- name: Prepare Maven Config Map
  template:
    src: nexus-maven-settings-configmap.yaml.j2
    dest: "{{ nexus_output_directory }}/nexus-maven-settings-configmap.yaml"
    mode: u+rwx

- name: Add the Nexus maven config map
  k8s:
    api_key: "{{ nexus_k8s_api_key | default(omit) }}"
    host: "{{ nexus_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ nexus_output_directory }}/nexus-maven-settings-configmap.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15
