################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cp4a-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cp4a-operator
  publisher: IBM
  sourceType: grpc
  image: cp.stg.icr.io/cp/cp4a/ibm-cp-automation-catalog@sha256:eeb912caf2c6e9021dfe8b32e7840b77950462daf5a2cfd6ab089c1d930f9704
  updateStrategy:
    registryPoll:
      interval: 45m
---

apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: iaf-operators
  namespace: openshift-marketplace
spec:
  displayName: IAF Operators
  publisher: IBM
  sourceType: grpc
  image: cp.stg.icr.io/cp/ibm-cp-automation-foundation-catalog:1.3.1
  updateStrategy:
    registryPoll:
      interval: 45m

---

apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: iaf-core-operators
  namespace: openshift-marketplace
spec:
  displayName: IAF Core Operators
  publisher: IBM
  sourceType: grpc
  image: cp.stg.icr.io/cp/ibm-automation-foundation-core-catalog:1.3.1
  updateStrategy:
    registryPoll:
      interval: 45m
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: opencloud-operators
  namespace: openshift-marketplace
spec:
  displayName: IBMCS Operators
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-common-service-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m

