- name: Execute Catalog Source role as prerequisite
  include_role:
    name: catalog_source
  vars:
    catalog_source_k8s_api_key: "{{ asset_repo_k8s_api_key | default(omit) }}"
    catalog_source_k8s_host: "{{ asset_repo_k8s_host | default(omit) }}"

- name: Create Asset Repo directory for generated files
  file:
    path: "{{ asset_repo_output_directory }}"
    state: directory
    mode: u+rwx

- name: Prepare yaml file for the Operator Subscription
  template:
    src: subscription.yaml.j2
    dest: "{{ asset_repo_output_directory }}/subscription.yaml"
    mode: u+rwx

- name: Add the Operator Subscription
  k8s:
    api_key: "{{ asset_repo_k8s_api_key | default(omit) }}"
    host: "{{ asset_repo_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ asset_repo_output_directory }}/subscription.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Manage Manual Operator ibm-integration-asset-repository in {{ asset_repo_project_name }}
  include_role:
    name: common
    tasks_from: manage-manual-operator
  vars:
    common_k8s_api_key: "{{ asset_repo_k8s_api_key | default(omit)  }}"
    common_k8s_host: "{{ asset_repo_k8s_host | default(omit) }}"
    common_namespace_name: "{{ asset_repo_project_name }}"
    common_label_selector_stub: ibm-integration-asset-repository

- name: Wait for AssetRepository CRD to be Established
  include_role:
    name: common
    tasks_from: wait-crd
  vars:
    common_k8s_api_key: "{{ asset_repo_k8s_api_key | default(omit)  }}"
    common_k8s_host: "{{ asset_repo_k8s_host | default(omit) }}"
    common_crd_name: assetrepositories.integration.ibm.com

- name: Prepare yaml file for AssetRepository instance
  template:
    src: assetrepository.yaml.j2
    dest: "{{ asset_repo_output_directory }}/assetrepository.yaml"
    mode: u+rwx

- name: Add AssetRepository instance
  k8s:
    api_key: "{{ asset_repo_k8s_api_key | default(omit) }}"
    host: "{{ asset_repo_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ asset_repo_output_directory }}/assetrepository.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Wait for AssetRepository to be Ready
  include_role:
    name: common
    tasks_from: wait-resource-condition-generic
  vars:
    common_k8s_api_key: "{{ asset_repo_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ asset_repo_k8s_host | default(omit) }}"
    common_api_version: integration.ibm.com/v1beta1
    common_resource_kind: AssetRepository
    common_resource_name: assets
    common_resource_namespace: "{{ asset_repo_project_name }}"
    common_condition_query: resources[*].status.phase
    common_condition_value: Ready
    common_retries: 30
    common_delay: 120

- name: Assign roles
  include_tasks: assign-roles.yml
