- name: Get AssetRepository CRD
  k8s_info:
    api_key: "{{ asset_repo_k8s_api_key | default(omit) }}"
    host: "{{ asset_repo_k8s_host | default(omit) }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: AssetRepository
  register: asset_repo_crd
  retries: 10
  delay: 1

- name: Delete AssetRepository instance
  k8s:
    state: absent
    api_key: "{{ asset_repo_k8s_api_key | default(omit) }}"
    host: "{{ asset_repo_k8s_host | default(omit) }}"
    api_version: integration.ibm.com/v1beta1
    kind: AssetRepository
    name: assets
    namespace: "{{ asset_repo_project_name }}"
    wait: true
    wait_sleep: 15
    wait_timeout: 120
  when: asset_repo_crd.resources | length != 0

- name: Get ibm-integration-asset-repository operator Subscription
  k8s_info:
    api_key: "{{ asset_repo_k8s_api_key | default(omit) }}"
    host: "{{ asset_repo_k8s_host | default(omit) }}"
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: ibm-integration-asset-repository
    namespace: "{{ asset_repo_project_name }}"
  register: subscription
  retries: 10
  delay: 1

- name: Get CSV
  set_fact:
    csv: '{{ subscription | json_query("resources[0].status.currentCSV") }}'

# Based on
# https://docs.openshift.com/container-platform/4.8/operators/admin/olm-deleting-operators-from-cluster.html#olm-deleting-operator-from-a-cluster-using-cli_olm-deleting-operators-from-a-cluster
- name: Remove ibm-integration-asset-repository operator Subscription
  k8s:
    api_key: "{{ asset_repo_k8s_api_key | default(omit) }}"
    host: "{{ asset_repo_k8s_host | default(omit) }}"
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: ibm-integration-asset-repository
    namespace: "{{ asset_repo_project_name }}"
    wait: true
    wait_sleep: 5
    wait_timeout: 50

- name: Remove ibm-integration-asset-repository operator CSV
  k8s:
    api_key: "{{ asset_repo_k8s_api_key | default(omit) }}"
    host: "{{ asset_repo_k8s_host | default(omit) }}"
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ csv }}"
    namespace: "{{ asset_repo_project_name }}"
    wait: true
    wait_sleep: 5
    wait_timeout: 50
  when: csv | length > 0
