apiVersion: processmining.ibm.com/v1beta1
kind: ProcessMining
metadata:
  name: processmining
spec:
  version: "{{PM_VERSION}}"
  license:
    accept: true
    cloudPak: "IBM Cloud Pak for Business Automation"
  defaultStorageClassName: "{{STORAGE_CLASS_NAME}}"
  processmining:
    tls:
      ui:
        secretname: pm-tls-secret
        certificate: tls.crt
        key: tls.key
        ca: ca.crt
    storage:
      database: 
        external: 
          host: "{{MONGODB_PM_HOSTNAME}}"
          port: 27017
          database: processmining
          user: root
          credential: 
            secretname: pm-dbs
            passwordkey: mongodbPassword
  taskmining:
    tls:
      ui:
        secretname: pm-tls-secret
        certificate: tls.crt
        key: tls.key
        ca: ca.crt      
    storage:
      database: 
        dbtype: db2
        external:
          credential:
            secretname: pm-dbs
            passwordkey: db2Password
          user: pm
          database: cp4ba
          host: "{{DB2_HOSTNAME}}"
          port: 50000
          schema: PM
          ssl: false        
