apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-common-service-operator
  namespace: common-service
spec:
  channel: "{{CPFS_OPERATOR_CHANNEL}}"
  installPlanApproval: Manual
  name: ibm-common-service-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: "{{CPFS_STARTING_CSV}}"  
