kind: Service
apiVersion: v1
metadata:
  name: cerebro
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: cerebro
  selector:
    app: cerebro
  type: ClusterIP
  sessionAffinity: None
