apiVersion: sonatype.com/v1alpha1
kind: NexusRepo
metadata:
  name: nexusrepo
spec:
  config:
    enabled: false
    mountPath: /sonatype-nexus-conf
  deployment:
    annotations: {}
    terminationGracePeriodSeconds: 120
  deploymentStrategy: {}
  ingress:
    annotations: {}
    enabled: false
    path: /
    tls:
      enabled: true
      secretName: nexus-tls
  nexus:
    dockerPort: 5003
    env:
      - name: install4jAddVmParams
        value: >-
          -Xms1200M -Xmx1200M -XX:MaxDirectMemorySize=2G
          -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
      - name: NEXUS_SECURITY_RANDOMPASSWORD
        value: 'false'
    hostAliases: []
    imageName: >-
      registry.connect.redhat.com/sonatype/nexus-repository-manager@sha256:4d816619ae0add7010dcc297d7593ceace9c92c060ed01764dd3d84e804c42f0
    imagePullPolicy: IfNotPresent
    imagePullSecret: ''
    livenessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      path: /
      periodSeconds: 30
    nexusPort: 8081
    podAnnotations: {}
    readinessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      path: /
      periodSeconds: 30
    resources: {}
    securityContext:
      fsGroup: 
    service:
      type: NodePort
  nexusProxyRoute:
    enabled: false
  persistence:
    accessMode: ReadWriteMany
    enabled: true
    storageSize: 8Gi
  replicaCount: 1
  route:
    enabled: false
    name: docker
    portName: docker
  secret:
    enabled: false
    mountPath: /etc/secret-volume
    readOnly: true
  service:
    annotations: {}
    enabled: false
    labels: {}
    ports:
      - name: nexus-service
        port: 80
        targetPort: 80
  statefulset:
    enabled: false
  tolerations: []
