- name: Get OCP Apps domain
  ansible.builtin.include_role:
    name: common
    tasks_from: apps-endpoint
  vars:
    common_k8s_api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ cp4ba_k8s_host | default(omit) }}"
    common_output_to_var: "apps_endpoint_domain"

# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.1?topic=tasks-business-automation-studio
# Get access token for ZEN administrative initial user
- name: Get Zen Initial Admin User Secret
  kubernetes.core.k8s_info:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    api_version: v1
    kind: Secret
    namespace: "{{ cp4ba_project_name }}"
    name: admin-user-details
  register: secret
  retries: 40
  delay: 15

# Based on introspection of Zen NGINX configs in Deployment ibm-nginx in /user-home/_global_/nginx-conf.d/icp4d-open-api-configmap.conf
# Based on CP4BA Operator code ansible\roles\AS-ID\tasks\iam-verify-and-add.yml@69+
- name: Get Zen Initial Admin User Acccess Token
  ansible.builtin.uri:
    url: "https://cpd-{{ cp4ba_project_name }}.{{ apps_endpoint_domain }}/icp4d-api/v1/authorize"
    method: POST
    body_format: json
    body:
      username: admin
      password: "{{ secret.resources[0].data.initial_admin_password | b64decode }}"
    validate_certs: false
    status_code: 200
  register: token_response

# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.1?topic=secrets-creating-custom-bpc-workforce-secret
- name: Get BPM Systems Federated Response
  ansible.builtin.uri:
    url: "https://cpd-{{ cp4ba_project_name }}.{{ apps_endpoint_domain }}/pfs/rest/bpm/federated/v1/systems"
    method: GET
    headers:
      Authorization: "Bearer {{ token_response.json | json_query('token') }}"
    validate_certs: false
    status_code:
      - 200
  register: bpm_systems_response

- name: Prepare yaml file for the Workforce Insights Secret
  ansible.builtin.template:
    src: bai/workforce-insights-config-secret.yaml.j2
    dest: "{{ cp4ba_output_directory }}/workforce-insights-config-secret.yaml"
    mode: u+rwx
  vars:
    system_type_query: json.federationResult[?systemType=='SYSTEM_TYPE_WLE']
    system_id: "{{ bpm_systems_response | json_query(system_type_query) | first | json_query('systemID') }}"
    username: cpadmin
    password: "{{ cp4ba_universal_password }}"
    url: "https://cpd-{{ cp4ba_project_name }}.{{ apps_endpoint_domain }}/bawaut"

- name: Add the Workforce Insights Secret
  kubernetes.core.k8s:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    src: "{{ cp4ba_output_directory }}/workforce-insights-config-secret.yaml"
    state: present
    merge_type: merge
    force: false
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Get BPC Pods
  kubernetes.core.k8s_info:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    api_version: v1
    kind: Pod
    namespace: "{{ cp4ba_project_name }}"
    label_selectors:
      - component = iaf-insights-engine-cockpit
  register: pods
  retries: 40
  delay: 15

- name: Delete BPC pods
  kubernetes.core.k8s:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    api_version: v1
    kind: Pod
    state: absent
    namespace: "{{ cp4ba_project_name }}"
    name: "{{ item.metadata.name }}"
  loop: "{{ pods.resources }}"

- name: Wait for BPC Deployment Available State
  ansible.builtin.include_role:
    name: common
    tasks_from: wait-resource-condition
  vars:
    common_k8s_api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ cp4ba_k8s_host | default(omit) }}"
    common_api_version: v1
    common_resource_kind: Deployment
    common_resource_name: iaf-insights-engine-cockpit
    common_resource_namespace: "{{ cp4ba_project_name }}"
    common_condition_name: Available
    common_retries: 80
    common_delay: 15
