- name: Get OCP Apps domain
  ansible.builtin.include_role:
    name: common
    tasks_from: apps-endpoint
  vars:
    common_k8s_api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ cp4ba_k8s_host | default(omit) }}"
    common_output_to_var: "apps_endpoint_domain"

- name: Get groups
  ansible.builtin.uri:
    url: "https://cpd-{{ cp4ba_project_name }}.{{ apps_endpoint_domain }}/usermgmt/v2/groups"
    method: GET
    headers:
      Authorization: "Bearer {{ token_response.json | json_query('token') }}"
    validate_certs: false
    status_code: 200
  register: groups_response

- name: Add ODM Admin role to {{ item }} group
  ansible.builtin.uri:
    url: "https://cpd-{{ cp4ba_project_name }}.{{ apps_endpoint_domain }}/usermgmt/v2/groups/{{ groups_response.json | json_query(condition_query) | first }}"
    method: PATCH
    headers:
      Authorization: "Bearer {{ token_response.json | json_query('token') }}"
    body_format: json
    body:
      add_role_identifiers:
        - odm_admin_role
        - odm_runtime_admin_role
        - odm_runtime_user_role
        - odm_business_user_role
    validate_certs: false
    status_code:
      - 200
      - 500
  vars:
    condition_query: "results[?name == '{{ item }}'].group_id"
  register: group_response
  failed_when: group_response.status == 500 and group_response.json | json_query('exception') is not search('.*duplicate key value*')
  with_items: "{{ lc_admin_groups }}"

- name: Add ODM Admin role to default admin user
  ansible.builtin.uri:
    url: "https://cpd-{{ cp4ba_project_name }}.{{ apps_endpoint_domain }}/usermgmt/v1/user/admin?add_roles=true"
    method: PUT
    headers:
      Authorization: "Bearer {{ token_response.json | json_query('token') }}"
    body_format: json
    body:
      username: "{{ lc_principal_admin_user }}"
      user_roles:
        - odm_admin_role
        - odm_runtime_admin_role
        - odm_runtime_user_role
        - odm_business_user_role
    validate_certs: false
    status_code:
      - 200
