# Counts on TLS from iaf-automationuiconfig

- name: Prepare yaml file for root CA Secret
  ansible.builtin.template:
    src: shared/root-ca-secret.yaml.j2
    dest: "{{ cp4ba_output_directory }}/root-ca-secret.yaml"
    mode: u+rwx

# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/21.0.3?topic=certificates-providing-root-ca-certificate
- name: Add root CA Secret
  kubernetes.core.k8s:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ cp4ba_output_directory }}/root-ca-secret.yaml"

# TODO verify if we need this when Zen front door is used. Maybe for External Share ingress Routes?
# echo
# echo ">>>>$(print_timestamp) Create wildcard certificate Secret"
# # Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/21.0.3?topic=certificates-providing-external-routes
# oc create secret tls cp4ba-wildcard --cert ../global-ca/wildcard.crt --key ../global-ca/wildcard.key
# # TODO needed the same for ADP CDS pod with different name, report bug, wait for fix. roles\common\tasks\fncm\fncm-ext-tls-certification.yml
# doesnt ganarate this secret, CDS deployment counts on it exist. temporarily resolved by omitting external_tls_certificate_secret from main cr.yaml
# # oc create secret tls cp4ba-fncm-ext-tls-secret --cert ../global-ca/wildcard.crt --key ../global-ca/wildcard.key

- name: Prepare yaml file for LDAP bind Secret
  ansible.builtin.template:
    src: shared/ldap-secret.yaml.j2
    dest: "{{ cp4ba_output_directory }}/ldap-secret.yaml"
    mode: u+rwx

- name: Add LDAP bind Secret
  kubernetes.core.k8s:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ cp4ba_output_directory }}/ldap-secret.yaml"
