apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: processmining-subscription
spec:
  channel: v1.0
  installPlanApproval: Automatic
  name: ibm-automation-processmining
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
