configuration:
  akhq:
    server:
      access-log:
        enabled: true
        name: org.akhq.log.access
secrets:
  akhq:
    connections:
      iaf-kafka:
        properties:
          bootstrap.servers: "iaf-system-kafka-bootstrap-{{CP4BA_PROJECT_NAME}}.{{OCP_APPS_ENDPOINT}}:443"
          security.protocol: SASL_SSL
          sasl.mechanism: SCRAM-SHA-512
          sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="cpadmin" password='{{UNIVERSAL_PASSWORD}}';
          ssl.truststore.location: /app/truststore.jks
          ssl.truststore.password: '{{UNIVERSAL_PASSWORD}}'
        # IAF avro not supported  
        #schema-registry:
        #  type: "confluent"
        #  url: "https://iaf-system-apicurio-{{CP4BA_PROJECT_NAME}}.{{OCP_APPS_ENDPOINT}}"
        #  basic-auth-username: cpadmin
        #  basic-auth-password: '{{UNIVERSAL_PASSWORD}}'
        #  properties:
        #    schema.registry.ssl.truststore.location: /app/truststore.jks
        #    schema.registry.ssl.truststore.password: '{{UNIVERSAL_PASSWORD}}'
kafkaSecrets:
  truststorejks: "{{TRUST_STORE}}"
extraVolumeMounts:
  - name: secrets
    mountPath: /app/truststore.jks
    subPath: truststorejks
readinessProbe:
  prefix: "" # set same as `micronaut.server.context-path`
