- name: Check if DB2 user already exists
  kubernetes.core.k8s_exec:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    namespace: db2
    pod: c-db2ucluster-db2u-0
    command: |
      id {{ item }}
  register: command_status
  ignore_errors: true

# Based on https://www.ibm.com/docs/en/db2/11.5?topic=ldap-managing-users
- name: Create DB2 user
  kubernetes.core.k8s_exec:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    namespace: db2
    pod: "{{ db2_ldap_pod_name }}"
    command: |
      /opt/ibm/ldap_scripts/addLdapUser.py -u {{ item }} -p {{ cp4ba_universal_password }} -r user
  register: command_status
  when: command_status.rc == 1 and command_status.stderr is search('.*no such user.*')
