# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/21.0.3?topic=openshift-installing-production-deployments

- name: Create CPFS directory for generated files
  file:
    path: "{{ cp4ba_output_directory }}"
    state: directory
    mode: u+rwx

- name: Repository
  include_tasks: repository.yml
  when: _cp4ba_run_repository == true

- name: DBs
  include_tasks: dbs.yml
  when: _cp4ba_run_dbs == true

- name: Predeploy
  include_tasks: predeploy.yml
  when: _cp4ba_run_predeploy == true
