# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/21.0.3?topic=openshift-installing-production-deployments

- name: Execute Catalog Source role as prerequisite
  ansible.builtin.include_role:
    name: catalog_source
  vars:
    catalog_source_k8s_api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    catalog_source_k8s_host: "{{ cp4ba_k8s_host | default(omit) }}"

- name: Repository
  include_tasks: repository.yml
  when: _cp4ba_run_repository

- name: DBs
  include_tasks: dbs.yml
  when: _cp4ba_run_dbs

- name: Predeploy
  include_tasks: predeploy.yml
  when: _cp4ba_run_predeploy

- name: Deploy
  block:

    - name: Deploy
      include_tasks: deploy.yml
      when: _cp4ba_run_deploy

  rescue:

    - name: CR & Log
      include_tasks: cr-log.yml
      when: _cp4ba_run_deploy

    - name: End play
      ansible.builtin.fail:
        msg: CP4BA deployment failed.

- name: Deploy CR & Log
  include_tasks: cr-log.yml
  when: _cp4ba_run_deploy

- name: Postdeploy
  include_tasks: postdeploy.yml
  when: _cp4ba_run_postdeploy
