apiVersion: apps/v1
kind: Deployment
metadata:
  name: db2mc
  labels:
    app: db2mc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db2mc
  template:
    metadata:
      labels:
        app: db2mc
    spec:
      containers:
        - name: db2mc
          image: "ibmcom/db2console:{{DB2MC_IMAGE_TAG}}"
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: db2mc
              mountPath: /mnt
            - name: tls
              readOnly: true
              mountPath: /opt/ibm-datasrvrmgr/certs
          env:
            - name: ADMIN_NAME
              value: cpadmin
            - name: ADMIN_PASSWORD
              value: '{{UNIVERSAL_PASSWORD}}'
            - name: LICENSE
              value: accept
          readinessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 45
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 200
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
      volumes:
        - name: db2mc
          persistentVolumeClaim:
            claimName: db2mc
        - name: tls
          secret:
            secretName: wildcard
            defaultMode: 256
