- name: Delete ProcessMining instance
  k8s:
    state: absent
    api_key: "{{ pm_k8s_api_key | default(omit) }}"
    host: "{{ pm_k8s_host | default(omit) }}"
    api_version: processmining.ibm.com/v1beta1
    kind: ProcessMining
    name: processmining
    namespace: "{{ pm_project_name }}"
    wait: true
    wait_sleep: 15
    wait_timeout: 120

- name: Delete {{ item }} Secret
  k8s:
    state: absent
    api_key: "{{ pm_k8s_api_key | default(omit) }}"
    host: "{{ pm_k8s_host | default(omit) }}"
    api_version: v1
    kind: Secret
    name: "{{ item }}"
    namespace: "{{ pm_project_name }}"
    wait: true
    wait_sleep: 15
    wait_timeout: 120
  with_items:
    - pm-dbs
    - pm-tls-secret

- name: Get processmining-subscription operator Subscription
  k8s_info:
    api_key: "{{ pm_k8s_api_key | default(omit) }}"
    host: "{{ pm_k8s_host | default(omit) }}"
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: processmining-subscription
    namespace: "{{ pm_project_name }}"
  register: subscription
  retries: 10
  delay: 1

- name: Get CSV
  set_fact:
    csv: '{{ subscription | json_query("resources[0].status.currentCSV") }}'

# Based on
# https://docs.openshift.com/container-platform/4.8/operators/admin/olm-deleting-operators-from-cluster.html#olm-deleting-operator-from-a-cluster-using-cli_olm-deleting-operators-from-a-cluster
- name: Remove rpa-subscription operator Subscription
  k8s:
    api_key: "{{ pm_k8s_api_key | default(omit) }}"
    host: "{{ pm_k8s_host | default(omit) }}"
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: processmining-subscription
    namespace: "{{ pm_project_name }}"
    wait: true
    wait_sleep: 5
    wait_timeout: 50

- name: Remove processmining-subscription operator CSV
  k8s:
    api_key: "{{ pm_k8s_api_key | default(omit) }}"
    host: "{{ pm_k8s_host | default(omit) }}"
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ csv }}"
    namespace: "{{ pm_project_name }}"
    wait: true
    wait_sleep: 5
    wait_timeout: 50
  when: csv | length > 0

- name: Delete Tablespaces
  kubernetes.core.k8s_exec:
    api_key: "{{ pm_k8s_api_key | default(omit) }}"
    host: "{{ pm_k8s_host | default(omit) }}"
    namespace: db2
    pod: c-db2ucluster-db2u-0
    command: |
      su - db2inst1 -c "
      db2 connect to CP4BA;
      db2 DROP TABLESPACE {{ item }};
      "
  register: command_status
  failed_when: command_status.rc == 4 and command_status.stdout is not search('.*\"'+item+'\" is an undefined name.*')
  with_items:
    - PM_TS
    - PM_TEMP_TS
    - PM_SYSTMP_TS

- name: Delete Schema
  kubernetes.core.k8s_exec:
    api_key: "{{ pm_k8s_api_key | default(omit) }}"
    host: "{{ pm_k8s_host | default(omit) }}"
    namespace: db2
    pod: c-db2ucluster-db2u-0
    command: |
      su - db2inst1 -c "
      db2 connect to CP4BA;
      db2 \"CALL SYSPROC.ADMIN_DROP_SCHEMA('PM', NULL, 'ERRORSCHEMA', 'ERRORTABLE')\"
      "
  register: command_status
  failed_when: command_status.rc == 4 and command_status.stdout is not search('.*-601:CREATE TABLE.*')

- name: Remove DB2 user
  include_role:
    name: common
    tasks_from: remove-db2-user
  vars:
    common_k8s_api_key: "{{ pm_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ pm_k8s_host | default(omit) }}"
    common_db2_user: pm

- name: Get Mongo DB pod
  kubernetes.core.k8s_info:
    api_key: "{{ pm_k8s_api_key | default(omit) }}"
    host: "{{ pm_k8s_host | default(omit) }}"
    api_version: v1
    kind: Pod
    namespace: mongodb
    label_selectors:
      - app.kubernetes.io/component=mongodb
  register: mongodb_pod

- name: Delete PM Mongo DB
  kubernetes.core.k8s_exec:
    api_key: "{{ pm_k8s_api_key | default(omit) }}"
    host: "{{ pm_k8s_host | default(omit) }}"
    namespace: mongodb
    pod: "{{ mongodb_pod.resources[0].metadata.name }}"
    command: >
      mongo --username root --password {{ pm_universal_password }} --authenticationDatabase admin
      --eval '{{ item }}' mongodb://localhost:27017/processmining
  register: command_status
  with_items:
    - db.dropUser("root")
    - db.dropDatabase()
