image:
  tag: "{{MONGODB_IMAGE_TAG}}"
architecture: standalone
auth:
  enabled: true
  rootPassword: "{{UNIVERSAL_PASSWORD}}"
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 256Mi
persistence:
  size: 8Gi
  storageClass: "{{STORAGE_CLASS_NAME}}"
arbiter:
  enabled: false
serviceAccount:
  create: false
