apiVersion: rpa.automation.ibm.com/v1beta1
kind: RoboticProcessAutomation
metadata:
  name: rpa
spec:
  license:
    accept: true
  version: "{{RPA_VERSION}}"
  tls:
    issuerRef:
      name: iaf-issuer
      kind: Issuer
    caSecret:
      secretName: global-ca
      key: ca.crt 
  api:
    externalConnection:
      secretName: rpa-db
    firstTenant:
      groupMappings:
        adminGroups: rpa-admins
        superAdminsGroups: rpa-superadmins
        userGroups: rpa-users
      name: ibm
      owner:
        email: cpadmin@cp.local
        name: cpadmin
    replicas: 1
    smtp:
      port: 587
      server: "{{MAIL_HOSTNAME}}"
      userSecret:
        secretName: rpa-smtp
    storage:
      hot:
        size: 7Gi
        class: "{{STORAGE_CLASS_NAME}}"
      archive:
        size: 11Gi
        class: "{{STORAGE_CLASS_NAME}}"
    # Following increases probes for ROKS        
    template:
      pod:
        spec:
          containers:
            - name: rpa-server
              readinessProbe:
                initialDelaySeconds: 100
              livenessProbe:
                initialDelaySeconds: 200            
  ui:
    replicas: 1
  ocr:
    replicas: 1
  antivirus:
    replicas: 1    
