apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rpa-subscription
spec:
  channel: v1.1
  installPlanApproval: Automatic
  name: ibm-automation-rpa
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
