- name: Remove Catalog Source
  k8s:
    state: absent
    api_key: "{{ mail_k8s_api_key | default(omit) }}"
    host: "{{ mail_k8s_host | default(omit) }}"
    api_version: v1alpha1
    kind: CatalogSource
    name: ibm-operator-catalog
    namespace: openshift-marketplace
    wait: yes
