# Based on https://github.com/tchiotludo/akhq

- name: Create AKHQ directory for generated files
  file:
    path: "{{ akhq_output_directory }}"
    state: directory
    mode: u+rwx

- name: Create Project
  include_role:
    name: common
    tasks_from: create-project
  vars:
    common_k8s_api_key: "{{ akhq_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ akhq_k8s_host | default(omit) }}"
    common_namespace_name: akhq
    common_output_directory: "{{ akhq_output_directory }}"

- name: Prepare yaml file for anyuid ClusterRoleBinding
  template:
    src: anyuid-scc-clusterrolebinding.yaml.j2
    dest: "{{ akhq_output_directory }}/anyuid-scc-clusterrolebinding.yaml"
    mode: u+rwx

- name: Add anyuid ClusterRoleBinding
  k8s:
    api_key: "{{ akhq_k8s_api_key | default(omit) }}"
    host: "{{ akhq_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ akhq_output_directory }}/anyuid-scc-clusterrolebinding.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Add helm-akhq chart repo
  kubernetes.core.helm_repository:
    name: helm-akhq
    repo_url: "https://akhq.io/"

- name: Check that the {{ akhq_ca_key_path }} exists
  stat:
    path: "{{ akhq_ca_key_path }}"
  register: akhq_ca_key_file

- name: Check that the {{ akhq_ca_crt_path }} exists
  stat:
    path: "{{ akhq_ca_crt_path }}"
  register: akhq_ca_crt_file

- name: Ensure we have CA keypair
  include_role:
    name: global_ca
  when: not akhq_ca_key_file.stat.exists or not akhq_ca_crt_file.stat.exists

# TODO JKS without private key of CA would be more appropriate
- name: Generate PKCS#12 file
  community.crypto.openssl_pkcs12:
    action: export
    path: "{{ akhq_output_directory }}/truststore.p12"
    friendly_name: global-ca
    certificate_path: "{{ akhq_ca_crt_path }}"
    privatekey_path: "{{ akhq_ca_key_path }}"
    passphrase: "{{ akhq_universal_password }}"
    state: present
    return_content: true
    mode: u+rwx
  register: p12

- name: Get data and store as fact
  set_fact:
    _p12: "{{ p12.pkcs12 }}"

- name: Get OCP Apps Endpoint
  include_role:
    name: common
    tasks_from: apps-endpoint
  vars:
    common_k8s_api_key: "{{ akhq_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ akhq_k8s_host | default(omit) }}"
    common_output_to_var: "apps_endpoint_domain"
  when: apps_endpoint_domain is not defined

- name: Prepare yaml file for values of helm chart
  template:
    src: values.yaml.j2
    dest: "{{ akhq_output_directory }}/values.yaml"
    mode: u+rwx

- name: Deploy akhq chart using values files on target
  kubernetes.core.helm:
    api_key: "{{ akhq_k8s_api_key | default(omit) }}"
    host: "{{ akhq_k8s_host | default(omit) }}"
    name: akhq
    chart_ref: helm-akhq/akhq
    chart_version: "{{ akhq_chart_version }}"
    release_namespace: akhq
    values_files:
      - "{{ akhq_output_directory }}/values.yaml"

- name: Crete Edge Route
  include_role:
    name: common
    tasks_from: create-edge-route
  vars:
    common_k8s_api_key: "{{ akhq_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ akhq_k8s_host | default(omit) }}"
    common_namespace_name: akhq
    common_route_name: akhq
    common_service_name: akhq
    common_wildcard_crt_path: "{{ akhq_wildcard_crt_path }}"
    common_wildcard_key_path: "{{ akhq_wildcard_key_path }}"
    common_ca_crt_path: "{{ akhq_ca_crt_path }}"
    common_apps_endpoint_domain: "{{ apps_endpoint_domain }}"
    common_output_directory: "{{ akhq_output_directory }}"

- name: Wait for akhq Deployment to be Available
  include_role:
    name: common
    tasks_from: wait-resource-condition
  vars:
    common_k8s_api_key: "{{ akhq_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ akhq_k8s_host | default(omit) }}"
    common_api_version: apps/v1
    common_resource_kind: Deployment
    common_resource_name: akhq
    common_resource_namespace: akhq
    common_condition_name: Available
    common_retries: 60
    common_delay: 15
