---
- name: CP4BA Enterprise
  hosts: localhost
  connection: local
  gather_facts: false  
  vars_files:
    - variables.yml  
    - internal-variables.yml
  tasks:
    # - name: Global CA
    #   include_role:
    #     name: global-ca

    - name: Catalog Source
      include_role:
        name: catalog-source
      vars: 
        catalog_source_k8s_api_key: "{{ ocp_cluster_token }}"
        catalog_source_k8s_host: "{{ ocp_api_endpoint }}"
        catalog_source_action: "{{ action }}"
