---
collections:
  - name: https://github.com/ansible-collections/kubernetes.core
    version: 2.2.0
    type: git
  - name: https://github.com/ansible-collections/community.crypto
    version: 2.2.2
    type: git