- name: ICR Password should be defined
  fail:
    msg: "The icr_password variable has to be defined."
  when: icr_password is not defined

- name: ICR Password should not be empty
  fail:
    msg: "The icr_password is not correct, it shouldn't be empty."
  when: not icr_password or icr_password | length == 0

- name: ICR Password should not be TODO_ICR_PASSWORD
  fail:
    msg: "The icr_password is not correct, it shouldn't be TODO_ICR_PASSWORD."
  when: icr_password is regex(".*TODO_ICR_PASSWORD.*")
