- name: Get RoboticProcessAutomation CRD
  k8s_info:
    api_key: "{{ rpa_k8s_api_key | default(omit) }}"
    host: "{{ rpa_k8s_host | default(omit) }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: RoboticProcessAutomation
  register: rpa_crd
  retries: 10
  delay: 1

- name: Delete RoboticProcessAutomation instance
  k8s:
    state: absent
    api_key: "{{ rpa_k8s_api_key | default(omit) }}"
    host: "{{ rpa_k8s_host | default(omit) }}"
    api_version: rpa.automation.ibm.com/v1beta1
    kind: RoboticProcessAutomation
    name: rpa
    namespace: "{{ rpa_project_name }}"
    wait: true
    wait_sleep: 15
    wait_timeout: 120
  when: rpa_crd.resources | length != 0

- name: Delete Deployments
  k8s:
    state: absent
    api_key: "{{ rpa_k8s_api_key | default(omit) }}"
    host: "{{ rpa_k8s_host | default(omit) }}"
    api_version: apps/v1
    kind: Deployment
    name: "{{ item }}"
    namespace: "{{ rpa_project_name }}"
    wait: true
    wait_sleep: 15
    wait_timeout: 120
  with_items:
    - rpa-ui-rpa
    - rpa-apiserver-rpa

- name: Delete Secrets
  k8s:
    state: absent
    api_key: "{{ rpa_k8s_api_key | default(omit) }}"
    host: "{{ rpa_k8s_host | default(omit) }}"
    api_version: v1
    kind: Secret
    name: "{{ item }}"
    namespace: "{{ rpa_project_name }}"
    wait: true
    wait_sleep: 15
    wait_timeout: 120
  with_items:
    - rpa-db
    - rpa-smtp
    - rpa-apiserver-rpa-dashboard

- name: Get MSSQL Pod
  k8s_info:
    api_key: "{{ rpa_k8s_api_key | default(omit) }}"
    host: "{{ rpa_k8s_host | default(omit) }}"
    api_version: v1
    kind: Pod
    namespace: mssql
    label_selectors:
      - app=mssql
  register: pods
  retries: 40
  delay: 15

- name: Delete MSSQL DBs
  kubernetes.core.k8s_exec:
    api_key: "{{ rpa_k8s_api_key | default(omit) }}"
    host: "{{ rpa_k8s_host | default(omit) }}"
    namespace: mssql
    pod: "{{ pods.resources[0].metadata.name }}"
    command: >
      /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "{{ rpa_universal_password }}" -Q
      "ALTER DATABASE [automation] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
      drop database [automation];
      ALTER DATABASE [knowledge] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
      drop database [knowledge];
      ALTER DATABASE [wordnet] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
      drop database [wordnet];
      ALTER DATABASE [address] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
      drop database [address];
      ALTER DATABASE [audit] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
      drop database [audit]"
  register: command_status
  when: pods.resources | length != 0

- name: Get rpa-subscription operator Subscription
  k8s_info:
    api_key: "{{ rpa_k8s_api_key | default(omit) }}"
    host: "{{ rpa_k8s_host | default(omit) }}"
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: rpa-subscription
    namespace: "{{ rpa_project_name }}"
  register: subscription
  retries: 10
  delay: 1

- name: Get CSV
  set_fact:
    csv: '{{ subscription | json_query("resources[0].status.currentCSV") }}'

# Based on
# https://docs.openshift.com/container-platform/4.8/operators/admin/olm-deleting-operators-from-cluster.html#olm-deleting-operator-from-a-cluster-using-cli_olm-deleting-operators-from-a-cluster
- name: Remove rpa-subscription operator Subscription
  k8s:
    api_key: "{{ rpa_k8s_api_key | default(omit) }}"
    host: "{{ rpa_k8s_host | default(omit) }}"
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: rpa-subscription
    namespace: "{{ rpa_project_name }}"
    wait: true
    wait_sleep: 5
    wait_timeout: 50

- name: Remove rpa-subscription operator CSV
  k8s:
    api_key: "{{ rpa_k8s_api_key | default(omit) }}"
    host: "{{ rpa_k8s_host | default(omit) }}"
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ csv }}"
    namespace: "{{ rpa_project_name }}"
    wait: true
    wait_sleep: 5
    wait_timeout: 50
  when: csv | length > 0
