- name: Wait for Operator Subscription '{{ manage_manual_operator_subscription }}'
  k8s_info:
    api_key: "{{ manage_manual_operator_k8s_api_key | default(omit) }}"
    host: "{{ manage_manual_operator_k8s_host | default(omit) }}"
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "{{ manage_manual_operator_subscription }}"
    namespace: "{{ manage_manual_operator_namespace }}"
  register: subscription
  retries: 10
  delay: 1
  until: ('InstallPlan' in subscription | json_query(condition_query) | unique)
  vars:
    condition_query: 'resources[*].status.installplan.kind'

- block:
    - name: Get Install Plan Resource name
      set_fact:
        install_plan_name: "{{ subscription | json_query('resources[0].status.installplan.name') }}"

    - name: Approve Install Plan
      k8s:
        api_key: "{{ manage_manual_operator_k8s_api_key | default(omit) }}"
        host: "{{ manage_manual_operator_k8s_host | default(omit) }}"
        state: present
        api_version: operators.coreos.com/v1alpha1
        kind: InstallPlan
        name: "{{ install_plan_name }}"
        namespace: "{{ manage_manual_operator_namespace }}"
        definition:
          spec:
            approved: true

  when: subscription | json_query(condition_query) | length == 0
  vars:
    condition_query: 'resources[*].status.installedCSV'

- name: Wait for Operator Deployment {{ manage_manual_operator_deployment }} to be Available
  k8s_info:
    api_key: "{{ manage_manual_operator_k8s_api_key | default(omit) }}"
    host: "{{ manage_manual_operator_k8s_host | default(omit) }}"
    api_version: v1
    kind: Deployment
    name: "{{ manage_manual_operator_deployment }}"
    namespace: "{{ manage_manual_operator_namespace }}"
  register: deployment
  retries: 10
  delay: 1
  until: ('True' in deployment | json_query(condition_query) | unique )
  vars:
    condition_query: "resources[0].status.conditions[?type == 'Available'].status"
