- name: Remove Project roundcube
  k8s:
    state: absent
    api_key: "{{ roundcube_k8s_api_key | default(omit) }}"
    host: "{{ roundcube_k8s_host | default(omit) }}"
    api_version: project.openshift.io/v1
    kind: Project
    name: roundcube
    wait: true
    wait_sleep: 15
    wait_timeout: 120
