apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-pm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express-pm
  template:
    metadata:
      labels:
        app: mongo-express-pm
    spec:
      containers:
        - name: mongo-express-pm
          image: "mongo-express:{{MONGO_EXPRESS_PM_IMAGE_TAG}}"
          imagePullPolicy: IfNotPresent
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10                       
          ports:
            - name: ui
              containerPort: 8081
              protocol: TCP
          env:
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "root"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "{{UNIVERSAL_PASSWORD}}"
            - name: ME_CONFIG_MONGODB_SERVER
              value: "{{MONGODB_PM_HOSTNAME}}"
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: "cpadmin"
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: "{{UNIVERSAL_PASSWORD}}"
