- name: Wait for '{{ wait_crd_name }}' CRD to be Established
  k8s_info:
    api_key: "{{ wait_crd_k8s_api_key | default(omit) }}"
    host: "{{ wait_crd_k8s_host | default(omit) }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: "{{ wait_crd_name }}"
  register: crd
  retries: 10
  delay: 1
  until: ('True' in crd | json_query(condition_query) | unique )
  vars:
    condition_query: "resources[0].status.conditions[?type == 'Established'].status"
