- name: Create Catalog Source directory for generated files
  file:
    path: "{{ openldap_output_directory }}"
    state: directory

- name: Prepare yaml file for Project
  template:
    src: project.yaml.j2
    dest: "{{ openldap_output_directory }}/project.yaml"

- name: Add Project
  k8s:
    api_key: "{{ openldap_k8s_api_key | default(omit)}}"
    host: "{{openldap_k8s_host | default(omit)}}"
    state: present
    force: False
    merge_type: merge
    src: "{{ openldap_output_directory }}/project.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Wait for Project
  k8s_info:
    api_key: "{{ openldap_k8s_api_key | default(omit) }}"
    host: "{{ openldap_k8s_host | default(omit) }}"
    api_version: project.openshift.io/v1
    kind: Project
    name: openldap
  register: project
  retries: 10
  delay: 1
  until: ('Active' in project | json_query(phase_query) | unique)
  vars:
    phase_query: 'resources[*].status.phase' 