# Based on https://www.ibm.com/docs/en/cpfs?topic=online-uninstalling-foundational-services

- name: Get IBM Cloud Pak foundational services operator Subscription
  k8s_info:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: ibm-common-service-operator
    namespace: ibm-common-services
  register: subscription
  retries: 10
  delay: 1

- name: Get CSV
  set_fact:
    csv: '{{ subscription | json_query("resources[0].status.currentCSV") }}'

# Based on
# https://docs.openshift.com/container-platform/4.8/operators/admin/olm-deleting-operators-from-cluster.html#olm-deleting-operator-from-a-cluster-using-cli_olm-deleting-operators-from-a-cluster
- name: Remove IBM Cloud Pak foundational services operator Subscription
  k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: ibm-common-service-operator
    namespace: ibm-common-services
    wait: true
    wait_sleep: 5
    wait_timeout: 50

- name: Remove IBM Cloud Pak foundational services operator CSV
  k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ csv }}"
    namespace: ibm-common-services
    wait: true
    wait_sleep: 5
    wait_timeout: 50
  when: csv | length > 0

- name: Remove common-service Project
  k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: common-service
    wait: true
    wait_sleep: 5
    wait_timeout: 50

- name: Remove OperandRequest common-service
  k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: operator.ibm.com/v1alpha1
    kind: OperandRequest
    name: common-service
    namespace: ibm-common-services
    wait: true
    wait_sleep: 5
    wait_timeout: 180

- name: Get all OperandRequest
  k8s_info:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    api_version: operator.ibm.com/v1alpha1
    kind: OperandRequest
    namespace: ibm-common-services
  register: operand_requests
  retries: 10
  delay: 1

- name: Wait All OperandRequest disappear
  k8s_info:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    api_version: operator.ibm.com/v1alpha1
    kind: OperandRequest
    name: "{{ item.metadata.name }}"
    namespace: ibm-common-services
  with_items: "{{ operand_requests.resources }}"
  register: operand_request
  retries: 40
  delay: 30
  until: operand_request.resources | length == 0

- name: Remove OperandConfig common-service
  k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: operator.ibm.com/v1alpha1
    kind: OperandConfig
    name: common-service
    namespace: ibm-common-services
  retries: 15
  delay: 2

- name: Remove OperandRegistry common-service
  k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: operator.ibm.com/v1alpha1
    kind: OperandRegistry
    name: common-service
    namespace: ibm-common-services
  retries: 15
  delay: 2

- name: Get all NamespaceScope
  k8s_info:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    api_version: operator.ibm.com/v1
    kind: NamespaceScope
    namespace: ibm-common-services
  register: namespace_scopes
  retries: 10
  delay: 1

- name: Delete All NamespaceScope
  k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: operator.ibm.com/v1
    kind: NamespaceScope
    name: "{{ item.metadata.name }}"
    namespace: ibm-common-services
    wait: true
    wait_sleep: 5
    wait_timeout: 180
  with_items: "{{ namespace_scopes.resources }}"

- name: Get Operand Deployment Lifecycle Manager operator Subscription
  k8s_info:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: operand-deployment-lifecycle-manager-app
    namespace: ibm-common-services
  register: subscription
  retries: 10
  delay: 1

- name: Get CSV
  set_fact:
    csv: '{{ subscription | json_query("resources[0].status.currentCSV") }}'

# Based on
# https://docs.openshift.com/container-platform/4.8/operators/admin/olm-deleting-operators-from-cluster.html#olm-deleting-operator-from-a-cluster-using-cli_olm-deleting-operators-from-a-cluster
- name: Remove Operand Deployment Lifecycle Manager operator Subscription
  k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: operand-deployment-lifecycle-manager-app
    namespace: ibm-common-services
    wait: true
    wait_sleep: 5
    wait_timeout: 50

- name: Remove Operand Deployment Lifecycle Manager operator CSV
  k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ csv }}"
    namespace: ibm-common-services
    wait: true
    wait_sleep: 5
    wait_timeout: 50
  when: csv | length > 0

- name: Remove ibmcloud-cluster-ca-cert Secret
  k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: v1
    kind: Secret
    name: ibmcloud-cluster-ca-cert
    namespace: kube-public
    wait: true
    wait_sleep: 5
    wait_timeout: 50

- name: Remove ibm-common-service-webhook-configuration MutatingWebhookConfiguration
  k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    name: ibm-common-service-webhook-configuration
    wait: true
    wait_sleep: 5
    wait_timeout: 50

- name: Remove services Project
  k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: services
    wait: true
    wait_sleep: 5
    wait_timeout: 50

- name: Remove ibm-common-services Project
  k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: ibm-common-services
    wait: true
    wait_sleep: 5
    wait_timeout: 50

- name: Get Cluster Monitoring ConfigMap
  k8s_info:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    kind: ConfigMap
    name: cluster-monitoring-config
    namespace: openshift-monitoring
  register: configmap
  retries: 10
  delay: 1

- name: Remove Cluster Monitoring ConfigMap
  k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    force: false
    merge_type: merge
    name: cluster-monitoring-config
    namespace: openshift-monitoring
    wait: true
    wait_sleep: 15
    wait_timeout: 15
  when: configmap | json_query('resources[0].data.automagic') | bool
