# Example of the functionality call
#
# - name: Nexus upload
#   include_role:
#     name: common
#     tasks_from: nexus-upload
#   vars:
#     common_k8s_api_key: "{{ prefix_k8s_api_key | default(omit) }}"
#     common_k8s_host: "{{ prefix_k8s_host | default(omit) }}"
#     common_file_folder_path: _file_folder_path
#     common_file_name: _file_name
#     common_universal_password: "{{ prefix_universal_password }}"

- name: Get OCP Apps domain
  include_role:
    name: common
    tasks_from: apps-endpoint
  vars:
    common_output_to_var: "apps_endpoint_domain"

- name: Upload to Nexus
  command: |
    curl -kX 'POST' \
    'https://nexus.{{ apps_endpoint_domain }}/service/rest/v1/components?repository=raw-hosted' \
    -H 'accept: application/json' \
    -H 'Content-Type: multipart/form-data' \
    -F 'raw.directory=cp4ba' \
    -F 'raw.asset1=@{{ common_file_folder_path }}/{{ common_file_name }}' \
    -F 'raw.asset1.filename={{ common_file_name }}' \
    --user "cpadmin:{{ common_universal_password }}" \
    -s -o /dev/null -w "%{http_code}"
  register: import_curl_result
  failed_when: import_curl_result.stdout != "204"
  changed_when: true
