# Example of the functionality call
#
# - name: Remove Operator
#   include_role:
#     name: common
#     tasks_from: remove-operator
#   vars:
#     common_k8s_api_key: "{{ prefix_k8s_api_key | default(omit) }}"
#     common_k8s_host: "{{ prefix_k8s_host | default(omit) }}"
#     common_namespace_name:_namespace_name
#     common_label_selector_stub: _label_selector_stub

- name: Set label_selectors
  set_fact:
    common_label_selector: "{{ ('operators.coreos.com/'+common_label_selector_stub+'.'+common_namespace_name)[:84] }}"

- name: Get Operator Subscription
  k8s_info:
    api_key: "{{ common_k8s_api_key | default(omit) }}"
    host: "{{ common_k8s_host | default(omit) }}"
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    label_selectors:
      - "{{ common_label_selector }}"
    namespace: "{{ common_namespace_name }}"
  register: subscription
  retries: 10
  delay: 1

- name: Get CSV
  set_fact:
    common_csvs: '{{ subscription | json_query("resources[*].status.currentCSV") }}'
    common_subscription_names: '{{ subscription | json_query("resources[*].metadata.name") }}'

# Based on
# https://docs.openshift.com/container-platform/4.8/operators/admin/olm-deleting-operators-from-cluster.html#olm-deleting-operator-from-a-cluster-using-cli_olm-deleting-operators-from-a-cluster
- name: Remove Operator Subscription
  k8s:
    api_key: "{{ common_k8s_api_key | default(omit) }}"
    host: "{{ common_k8s_host | default(omit) }}"
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "{{ common_subscription_name }}"
    namespace: "{{ common_namespace_name }}"
    wait: true
    wait_sleep: 5
    wait_timeout: 50
  loop: "{{ common_subscription_names }}"
  loop_control:
    loop_var: common_subscription_name

- name: Remove Operator CSV
  k8s:
    api_key: "{{ common_k8s_api_key | default(omit) }}"
    host: "{{ common_k8s_host | default(omit) }}"
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ common_csv }}"
    namespace: "{{ common_namespace_name }}"
    wait: true
    wait_sleep: 5
    wait_timeout: 50
  loop: "{{ common_csvs }}"
  loop_control:
    loop_var: common_csv

- name: Wait for {{ common_label_selector }} Deployment to terminate
  k8s_info:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ common_namespace_name }}"
    label_selectors:
      - "{{ common_label_selector }}"
  register: deployments
  retries: 60
  delay: 30
  until: deployments.resources | length == 0

- name: Get Role Bindings left by Operator for label {{ common_label_selector }}
  k8s_info:
    api_key: "{{ common_k8s_api_key | default(omit) }}"
    host: "{{ common_k8s_host | default(omit) }}"
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    namespace: "{{ common_namespace_name }}"
    label_selectors:
      - "{{ common_label_selector }}"
  register: common_leftover_role_bindings
  retries: 10
  delay: 1

- name: Remove leftover Role Bindings {{ item }}
  k8s:
    api_key: "{{ common_k8s_api_key | default(omit) }}"
    host: "{{ common_k8s_host | default(omit) }}"
    state: absent
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    name: "{{ common_leftover_role_binding.metadata.name }}"
    namespace: "{{ common_namespace_name }}"
    wait: true
    wait_sleep: 5
    wait_timeout: 50
  loop: "{{ common_leftover_role_bindings.resources }}"
  loop_control:
    loop_var: common_leftover_role_binding
