apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "{{STORAGE_CLASS_NAME}}"
  resources:
    requests:
      storage: 5Gi
